name: PR Merge

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/version.rb'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Cache bundle install
      uses: actions/cache@v1
      with:
        path: ~/.bundle 
        key: ${{ runner.os }}-bundler-${{ hashFiles('**/*.gemspec') }}
        restore-keys: |
          ${{ runner.os }}-bundler-${{ env.cache-name }}-
          ${{ runner.os }}-bundler-
          ${{ runner.os }}-
    - name: Bundle install
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Build and test with Rake
      run: bundle exec rake
